'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="AdventureWorksLT_Data")>  _
Partial Public Class AdventureWorksDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSalesOrderDetail(instance As SalesOrderDetail)
    End Sub
  Partial Private Sub UpdateSalesOrderDetail(instance As SalesOrderDetail)
    End Sub
  Partial Private Sub DeleteSalesOrderDetail(instance As SalesOrderDetail)
    End Sub
  Partial Private Sub InsertSalesOrderHeader(instance As SalesOrderHeader)
    End Sub
  Partial Private Sub UpdateSalesOrderHeader(instance As SalesOrderHeader)
    End Sub
  Partial Private Sub DeleteSalesOrderHeader(instance As SalesOrderHeader)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("AdventureWorksLT_DataConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SalesOrderDetails() As System.Data.Linq.Table(Of SalesOrderDetail)
		Get
			Return Me.GetTable(Of SalesOrderDetail)
		End Get
	End Property
	
	Public ReadOnly Property SalesOrderHeaders() As System.Data.Linq.Table(Of SalesOrderHeader)
		Get
			Return Me.GetTable(Of SalesOrderHeader)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="SalesLT.SalesOrderDetail")>  _
Partial Public Class SalesOrderDetail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _SalesOrderID As Integer
	
	Private _SalesOrderDetailID As Integer
	
	Private _OrderQty As Short
	
	Private _ProductID As Integer
	
	Private _UnitPrice As Decimal
	
	Private _UnitPriceDiscount As Decimal
	
	Private _LineTotal As Decimal
	
	Private _rowguid As System.Guid
	
	Private _ModifiedDate As Date
	
	Private _SalesOrderHeader As EntityRef(Of SalesOrderHeader)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSalesOrderIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSalesOrderIDChanged()
    End Sub
    Partial Private Sub OnSalesOrderDetailIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSalesOrderDetailIDChanged()
    End Sub
    Partial Private Sub OnOrderQtyChanging(value As Short)
    End Sub
    Partial Private Sub OnOrderQtyChanged()
    End Sub
    Partial Private Sub OnProductIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnProductIDChanged()
    End Sub
    Partial Private Sub OnUnitPriceChanging(value As Decimal)
    End Sub
    Partial Private Sub OnUnitPriceChanged()
    End Sub
    Partial Private Sub OnUnitPriceDiscountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnUnitPriceDiscountChanged()
    End Sub
    Partial Private Sub OnLineTotalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnLineTotalChanged()
    End Sub
    Partial Private Sub OnrowguidChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnrowguidChanged()
    End Sub
    Partial Private Sub OnModifiedDateChanging(value As Date)
    End Sub
    Partial Private Sub OnModifiedDateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SalesOrderHeader = CType(Nothing, EntityRef(Of SalesOrderHeader))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SalesOrderID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property SalesOrderID() As Integer
		Get
			Return Me._SalesOrderID
		End Get
		Set
			If ((Me._SalesOrderID = value)  _
						= false) Then
				If Me._SalesOrderHeader.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnSalesOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._SalesOrderID = value
				Me.SendPropertyChanged("SalesOrderID")
				Me.OnSalesOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SalesOrderDetailID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property SalesOrderDetailID() As Integer
		Get
			Return Me._SalesOrderDetailID
		End Get
		Set
			If ((Me._SalesOrderDetailID = value)  _
						= false) Then
				Me.OnSalesOrderDetailIDChanging(value)
				Me.SendPropertyChanging
				Me._SalesOrderDetailID = value
				Me.SendPropertyChanged("SalesOrderDetailID")
				Me.OnSalesOrderDetailIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderQty", DbType:="SmallInt NOT NULL")>  _
	Public Property OrderQty() As Short
		Get
			Return Me._OrderQty
		End Get
		Set
			If ((Me._OrderQty = value)  _
						= false) Then
				Me.OnOrderQtyChanging(value)
				Me.SendPropertyChanging
				Me._OrderQty = value
				Me.SendPropertyChanged("OrderQty")
				Me.OnOrderQtyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductID", DbType:="Int NOT NULL")>  _
	Public Property ProductID() As Integer
		Get
			Return Me._ProductID
		End Get
		Set
			If ((Me._ProductID = value)  _
						= false) Then
				Me.OnProductIDChanging(value)
				Me.SendPropertyChanging
				Me._ProductID = value
				Me.SendPropertyChanged("ProductID")
				Me.OnProductIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnitPrice", DbType:="Money NOT NULL")>  _
	Public Property UnitPrice() As Decimal
		Get
			Return Me._UnitPrice
		End Get
		Set
			If ((Me._UnitPrice = value)  _
						= false) Then
				Me.OnUnitPriceChanging(value)
				Me.SendPropertyChanging
				Me._UnitPrice = value
				Me.SendPropertyChanged("UnitPrice")
				Me.OnUnitPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnitPriceDiscount", DbType:="Money NOT NULL")>  _
	Public Property UnitPriceDiscount() As Decimal
		Get
			Return Me._UnitPriceDiscount
		End Get
		Set
			If ((Me._UnitPriceDiscount = value)  _
						= false) Then
				Me.OnUnitPriceDiscountChanging(value)
				Me.SendPropertyChanging
				Me._UnitPriceDiscount = value
				Me.SendPropertyChanged("UnitPriceDiscount")
				Me.OnUnitPriceDiscountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LineTotal", AutoSync:=AutoSync.Always, DbType:="Decimal(38,6) NOT NULL", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property LineTotal() As Decimal
		Get
			Return Me._LineTotal
		End Get
		Set
			If ((Me._LineTotal = value)  _
						= false) Then
				Me.OnLineTotalChanging(value)
				Me.SendPropertyChanging
				Me._LineTotal = value
				Me.SendPropertyChanged("LineTotal")
				Me.OnLineTotalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rowguid", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property rowguid() As System.Guid
		Get
			Return Me._rowguid
		End Get
		Set
			If ((Me._rowguid = value)  _
						= false) Then
				Me.OnrowguidChanging(value)
				Me.SendPropertyChanging
				Me._rowguid = value
				Me.SendPropertyChanged("rowguid")
				Me.OnrowguidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModifiedDate", DbType:="DateTime NOT NULL")>  _
	Public Property ModifiedDate() As Date
		Get
			Return Me._ModifiedDate
		End Get
		Set
			If ((Me._ModifiedDate = value)  _
						= false) Then
				Me.OnModifiedDateChanging(value)
				Me.SendPropertyChanging
				Me._ModifiedDate = value
				Me.SendPropertyChanged("ModifiedDate")
				Me.OnModifiedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SalesOrderHeader_SalesOrderDetail", Storage:="_SalesOrderHeader", ThisKey:="SalesOrderID", OtherKey:="SalesOrderID", IsForeignKey:=true, DeleteOnNull:=true, DeleteRule:="CASCADE")>  _
	Public Property SalesOrderHeader() As SalesOrderHeader
		Get
			Return Me._SalesOrderHeader.Entity
		End Get
		Set
			Dim previousValue As SalesOrderHeader = Me._SalesOrderHeader.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SalesOrderHeader.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SalesOrderHeader.Entity = Nothing
					previousValue.SalesOrderDetails.Remove(Me)
				End If
				Me._SalesOrderHeader.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SalesOrderDetails.Add(Me)
					Me._SalesOrderID = value.SalesOrderID
				Else
					Me._SalesOrderID = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("SalesOrderHeader")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="SalesLT.SalesOrderHeader")>  _
Partial Public Class SalesOrderHeader
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _SalesOrderID As Integer
	
	Private _RevisionNumber As Byte
	
	Private _OrderDate As Date
	
	Private _DueDate As Date
	
	Private _ShipDate As System.Nullable(Of Date)
	
	Private _Status As Byte
	
	Private _OnlineOrderFlag As Boolean
	
	Private _SalesOrderNumber As String
	
	Private _PurchaseOrderNumber As String
	
	Private _AccountNumber As String
	
	Private _CustomerID As Integer
	
	Private _ShipToAddressID As System.Nullable(Of Integer)
	
	Private _BillToAddressID As System.Nullable(Of Integer)
	
	Private _ShipMethod As String
	
	Private _CreditCardApprovalCode As String
	
	Private _SubTotal As Decimal
	
	Private _TaxAmt As Decimal
	
	Private _Freight As Decimal
	
	Private _TotalDue As Decimal
	
	Private _Comment As String
	
	Private _rowguid As System.Guid
	
	Private _ModifiedDate As Date
	
	Private _SalesOrderDetails As EntitySet(Of SalesOrderDetail)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSalesOrderIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSalesOrderIDChanged()
    End Sub
    Partial Private Sub OnRevisionNumberChanging(value As Byte)
    End Sub
    Partial Private Sub OnRevisionNumberChanged()
    End Sub
    Partial Private Sub OnOrderDateChanging(value As Date)
    End Sub
    Partial Private Sub OnOrderDateChanged()
    End Sub
    Partial Private Sub OnDueDateChanging(value As Date)
    End Sub
    Partial Private Sub OnDueDateChanged()
    End Sub
    Partial Private Sub OnShipDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnShipDateChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As Byte)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnOnlineOrderFlagChanging(value As Boolean)
    End Sub
    Partial Private Sub OnOnlineOrderFlagChanged()
    End Sub
    Partial Private Sub OnSalesOrderNumberChanging(value As String)
    End Sub
    Partial Private Sub OnSalesOrderNumberChanged()
    End Sub
    Partial Private Sub OnPurchaseOrderNumberChanging(value As String)
    End Sub
    Partial Private Sub OnPurchaseOrderNumberChanged()
    End Sub
    Partial Private Sub OnAccountNumberChanging(value As String)
    End Sub
    Partial Private Sub OnAccountNumberChanged()
    End Sub
    Partial Private Sub OnCustomerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerIDChanged()
    End Sub
    Partial Private Sub OnShipToAddressIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnShipToAddressIDChanged()
    End Sub
    Partial Private Sub OnBillToAddressIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBillToAddressIDChanged()
    End Sub
    Partial Private Sub OnShipMethodChanging(value As String)
    End Sub
    Partial Private Sub OnShipMethodChanged()
    End Sub
    Partial Private Sub OnCreditCardApprovalCodeChanging(value As String)
    End Sub
    Partial Private Sub OnCreditCardApprovalCodeChanged()
    End Sub
    Partial Private Sub OnSubTotalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnSubTotalChanged()
    End Sub
    Partial Private Sub OnTaxAmtChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTaxAmtChanged()
    End Sub
    Partial Private Sub OnFreightChanging(value As Decimal)
    End Sub
    Partial Private Sub OnFreightChanged()
    End Sub
    Partial Private Sub OnTotalDueChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalDueChanged()
    End Sub
    Partial Private Sub OnCommentChanging(value As String)
    End Sub
    Partial Private Sub OnCommentChanged()
    End Sub
    Partial Private Sub OnrowguidChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnrowguidChanged()
    End Sub
    Partial Private Sub OnModifiedDateChanging(value As Date)
    End Sub
    Partial Private Sub OnModifiedDateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SalesOrderDetails = New EntitySet(Of SalesOrderDetail)(AddressOf Me.attach_SalesOrderDetails, AddressOf Me.detach_SalesOrderDetails)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SalesOrderID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property SalesOrderID() As Integer
		Get
			Return Me._SalesOrderID
		End Get
		Set
			If ((Me._SalesOrderID = value)  _
						= false) Then
				Me.OnSalesOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._SalesOrderID = value
				Me.SendPropertyChanged("SalesOrderID")
				Me.OnSalesOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RevisionNumber", DbType:="TinyInt NOT NULL")>  _
	Public Property RevisionNumber() As Byte
		Get
			Return Me._RevisionNumber
		End Get
		Set
			If ((Me._RevisionNumber = value)  _
						= false) Then
				Me.OnRevisionNumberChanging(value)
				Me.SendPropertyChanging
				Me._RevisionNumber = value
				Me.SendPropertyChanged("RevisionNumber")
				Me.OnRevisionNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderDate", DbType:="DateTime NOT NULL")>  _
	Public Property OrderDate() As Date
		Get
			Return Me._OrderDate
		End Get
		Set
			If ((Me._OrderDate = value)  _
						= false) Then
				Me.OnOrderDateChanging(value)
				Me.SendPropertyChanging
				Me._OrderDate = value
				Me.SendPropertyChanged("OrderDate")
				Me.OnOrderDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DueDate", DbType:="DateTime NOT NULL")>  _
	Public Property DueDate() As Date
		Get
			Return Me._DueDate
		End Get
		Set
			If ((Me._DueDate = value)  _
						= false) Then
				Me.OnDueDateChanging(value)
				Me.SendPropertyChanging
				Me._DueDate = value
				Me.SendPropertyChanged("DueDate")
				Me.OnDueDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShipDate", DbType:="DateTime")>  _
	Public Property ShipDate() As System.Nullable(Of Date)
		Get
			Return Me._ShipDate
		End Get
		Set
			If (Me._ShipDate.Equals(value) = false) Then
				Me.OnShipDateChanging(value)
				Me.SendPropertyChanging
				Me._ShipDate = value
				Me.SendPropertyChanged("ShipDate")
				Me.OnShipDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="TinyInt NOT NULL")>  _
	Public Property Status() As Byte
		Get
			Return Me._Status
		End Get
		Set
			If ((Me._Status = value)  _
						= false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OnlineOrderFlag", DbType:="Bit NOT NULL")>  _
	Public Property OnlineOrderFlag() As Boolean
		Get
			Return Me._OnlineOrderFlag
		End Get
		Set
			If ((Me._OnlineOrderFlag = value)  _
						= false) Then
				Me.OnOnlineOrderFlagChanging(value)
				Me.SendPropertyChanging
				Me._OnlineOrderFlag = value
				Me.SendPropertyChanged("OnlineOrderFlag")
				Me.OnOnlineOrderFlagChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SalesOrderNumber", AutoSync:=AutoSync.Always, DbType:="NVarChar(25) NOT NULL", CanBeNull:=false, IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property SalesOrderNumber() As String
		Get
			Return Me._SalesOrderNumber
		End Get
		Set
			If (String.Equals(Me._SalesOrderNumber, value) = false) Then
				Me.OnSalesOrderNumberChanging(value)
				Me.SendPropertyChanging
				Me._SalesOrderNumber = value
				Me.SendPropertyChanged("SalesOrderNumber")
				Me.OnSalesOrderNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PurchaseOrderNumber", DbType:="NVarChar(25)")>  _
	Public Property PurchaseOrderNumber() As String
		Get
			Return Me._PurchaseOrderNumber
		End Get
		Set
			If (String.Equals(Me._PurchaseOrderNumber, value) = false) Then
				Me.OnPurchaseOrderNumberChanging(value)
				Me.SendPropertyChanging
				Me._PurchaseOrderNumber = value
				Me.SendPropertyChanged("PurchaseOrderNumber")
				Me.OnPurchaseOrderNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountNumber", DbType:="NVarChar(15)")>  _
	Public Property AccountNumber() As String
		Get
			Return Me._AccountNumber
		End Get
		Set
			If (String.Equals(Me._AccountNumber, value) = false) Then
				Me.OnAccountNumberChanging(value)
				Me.SendPropertyChanging
				Me._AccountNumber = value
				Me.SendPropertyChanged("AccountNumber")
				Me.OnAccountNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerID", DbType:="Int NOT NULL")>  _
	Public Property CustomerID() As Integer
		Get
			Return Me._CustomerID
		End Get
		Set
			If ((Me._CustomerID = value)  _
						= false) Then
				Me.OnCustomerIDChanging(value)
				Me.SendPropertyChanging
				Me._CustomerID = value
				Me.SendPropertyChanged("CustomerID")
				Me.OnCustomerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShipToAddressID", DbType:="Int")>  _
	Public Property ShipToAddressID() As System.Nullable(Of Integer)
		Get
			Return Me._ShipToAddressID
		End Get
		Set
			If (Me._ShipToAddressID.Equals(value) = false) Then
				Me.OnShipToAddressIDChanging(value)
				Me.SendPropertyChanging
				Me._ShipToAddressID = value
				Me.SendPropertyChanged("ShipToAddressID")
				Me.OnShipToAddressIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BillToAddressID", DbType:="Int")>  _
	Public Property BillToAddressID() As System.Nullable(Of Integer)
		Get
			Return Me._BillToAddressID
		End Get
		Set
			If (Me._BillToAddressID.Equals(value) = false) Then
				Me.OnBillToAddressIDChanging(value)
				Me.SendPropertyChanging
				Me._BillToAddressID = value
				Me.SendPropertyChanged("BillToAddressID")
				Me.OnBillToAddressIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShipMethod", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ShipMethod() As String
		Get
			Return Me._ShipMethod
		End Get
		Set
			If (String.Equals(Me._ShipMethod, value) = false) Then
				Me.OnShipMethodChanging(value)
				Me.SendPropertyChanging
				Me._ShipMethod = value
				Me.SendPropertyChanged("ShipMethod")
				Me.OnShipMethodChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreditCardApprovalCode", DbType:="VarChar(15)")>  _
	Public Property CreditCardApprovalCode() As String
		Get
			Return Me._CreditCardApprovalCode
		End Get
		Set
			If (String.Equals(Me._CreditCardApprovalCode, value) = false) Then
				Me.OnCreditCardApprovalCodeChanging(value)
				Me.SendPropertyChanging
				Me._CreditCardApprovalCode = value
				Me.SendPropertyChanged("CreditCardApprovalCode")
				Me.OnCreditCardApprovalCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubTotal", DbType:="Money NOT NULL")>  _
	Public Property SubTotal() As Decimal
		Get
			Return Me._SubTotal
		End Get
		Set
			If ((Me._SubTotal = value)  _
						= false) Then
				Me.OnSubTotalChanging(value)
				Me.SendPropertyChanging
				Me._SubTotal = value
				Me.SendPropertyChanged("SubTotal")
				Me.OnSubTotalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TaxAmt", DbType:="Money NOT NULL")>  _
	Public Property TaxAmt() As Decimal
		Get
			Return Me._TaxAmt
		End Get
		Set
			If ((Me._TaxAmt = value)  _
						= false) Then
				Me.OnTaxAmtChanging(value)
				Me.SendPropertyChanging
				Me._TaxAmt = value
				Me.SendPropertyChanged("TaxAmt")
				Me.OnTaxAmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Freight", DbType:="Money NOT NULL")>  _
	Public Property Freight() As Decimal
		Get
			Return Me._Freight
		End Get
		Set
			If ((Me._Freight = value)  _
						= false) Then
				Me.OnFreightChanging(value)
				Me.SendPropertyChanging
				Me._Freight = value
				Me.SendPropertyChanged("Freight")
				Me.OnFreightChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalDue", AutoSync:=AutoSync.Always, DbType:="Money NOT NULL", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property TotalDue() As Decimal
		Get
			Return Me._TotalDue
		End Get
		Set
			If ((Me._TotalDue = value)  _
						= false) Then
				Me.OnTotalDueChanging(value)
				Me.SendPropertyChanging
				Me._TotalDue = value
				Me.SendPropertyChanged("TotalDue")
				Me.OnTotalDueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comment", DbType:="NVarChar(MAX)")>  _
	Public Property Comment() As String
		Get
			Return Me._Comment
		End Get
		Set
			If (String.Equals(Me._Comment, value) = false) Then
				Me.OnCommentChanging(value)
				Me.SendPropertyChanging
				Me._Comment = value
				Me.SendPropertyChanged("Comment")
				Me.OnCommentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rowguid", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property rowguid() As System.Guid
		Get
			Return Me._rowguid
		End Get
		Set
			If ((Me._rowguid = value)  _
						= false) Then
				Me.OnrowguidChanging(value)
				Me.SendPropertyChanging
				Me._rowguid = value
				Me.SendPropertyChanged("rowguid")
				Me.OnrowguidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModifiedDate", DbType:="DateTime NOT NULL")>  _
	Public Property ModifiedDate() As Date
		Get
			Return Me._ModifiedDate
		End Get
		Set
			If ((Me._ModifiedDate = value)  _
						= false) Then
				Me.OnModifiedDateChanging(value)
				Me.SendPropertyChanging
				Me._ModifiedDate = value
				Me.SendPropertyChanged("ModifiedDate")
				Me.OnModifiedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SalesOrderHeader_SalesOrderDetail", Storage:="_SalesOrderDetails", ThisKey:="SalesOrderID", OtherKey:="SalesOrderID")>  _
	Public Property SalesOrderDetails() As EntitySet(Of SalesOrderDetail)
		Get
			Return Me._SalesOrderDetails
		End Get
		Set
			Me._SalesOrderDetails.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SalesOrderDetails(ByVal entity As SalesOrderDetail)
		Me.SendPropertyChanging
		entity.SalesOrderHeader = Me
	End Sub
	
	Private Sub detach_SalesOrderDetails(ByVal entity As SalesOrderDetail)
		Me.SendPropertyChanging
		entity.SalesOrderHeader = Nothing
	End Sub
End Class
